version: '3'

services:

  app:
    container_name: users_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: 8080
      DB_CONN: "postgres://postgresUser:postgresPW@db:5432/postgresDB?sslmode=disable"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: users_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgresUser"
      POSTGRES_PASSWORD: "postgresPW"
      POSTGRES_DB: "postgresDB"
      TZ: 'UTC'
      PGTZ: 'UTC'
