version: '3'

services:

  app:
    container_name: users_api
    image: earnestdscott/users-test
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - PORT
      - DB_CONN
      - RDS_HOSTNAME
      - RDS_PORT
      - RDS_DB_NAME
      - RDS_USERNAME
      - RDS_PASSWORD

    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: users_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
      - TZ=UTC
      - PGTZ=UTC
