version: '3'

services:

  app:
    container_name: users_api
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - ./env/users.env
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: users_db
    ports:
      - '5432:5432'
    env_file:
      - ./env/db.env
      