pipeline {
    environment {
imagename = "yenigul/hacicenkins"
registryCredential = 'dockerhub-creds'
}
    agent any
    stages {
        stage('pre-build') {
            steps {
                echo 'Build api and db images for testing ...'
            }
        }
        stage('build') {
            steps {
                echo 'Building production Docker image'
                sh '/usr/local/bin/docker-compose up --build'
                }
            }
        }
    }
}