pipeline {
    environment {
imagename = "yenigul/hacicenkins"
registryCredential = 'dockerhub-creds'
}
    agent any
    stages {
        stage('pre-build') {
            steps {
                echo 'Build api and db images for testing ...'
            }
        }
        stage('build') {
            steps {
                echo 'Building production Docker image'
                dir("users"){
                    sh 'docker compose build'
                    sh 'pwd'
                    sh 'docker tag users_app earnestdscott/users_app:latest'
                }
                withDockerRegistry([credentialsId: "dockerhub-creds", url: ""]){
                    sh 'docker push earnestdscott/users_app:latest'
                }
            }
        }
    }
}