pipeline {
    environment {
imagename = "yenigul/hacicenkins"
registryCredential = 'yenigul-dockerhub'
dockerImage = ''
}
    agent { any }
    stages {
        stage('pre-build') {
            steps {
                echo 'Build api and db images for testing ...'
            }
        }
        stage('build') {
            steps {
                echo 'Building production Docker image'
                dockerImage = docker.build('users', 'docker-compose.yaml')
            }
        }
    }
}